# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: CC-BY-NC-4.0
# evaluate VDST q-gen model with oracle_rcnn model + baseline guesser model
hparas:
  max_epoch: 30
  optimizer: "Adam"
  lr: 0.001
  lr_scheduler: "warmup"      # 'fixed'/'warmup'/'decay'
  clip_grad_norm: 5.0


data:
  tokenizer: "gw"
  vocab_path: "tf-pretrained-model/dict.json"
  batch_size: 32
  dataroot: "data"
  features_path: 
    "train": "data/rcnn/from_rcnn/"
    "valid": "data/rcnn/from_rcnn/"
    "test": "data/rcnn/from_rcnn/"
  features_path_gt: 
    "train": "data/rcnn/from_gt_gw_xyxy_scale/"
    "valid": "data/rcnn/from_gt_gw_xyxy_scale/"
    "test": "data/rcnn/from_gt_gw_xyxy_scale/"


model:
  qgen:
    pretrained_path: "ckpt/qgen_vdst-sd0/best.pth"
    wrd_embed_size: 512
    obj_feat_size: 2056
    lstm_hidden_size: 512
    num_bboxs: 36
    num_glimpses: 2

  oracle:
    pretrained_path: "ckpt/oracle_rcnn-sd0/best.pth"
    wrd_embed_size: 300
    wrd_hidden_size: 512
    img_feat_size: 2048
    img_hidden_size: 512
    spatial_size: 8
    num_cats: 100              # Number of catergories: 91 (actually)
    cat_embed_size: 512
    cat_pad_id: 0              # 1-91 is used
    mlp_hidden: 512
    num_classes: 3

  guesser:
    pretrained_path: "ckpt/guesser-sd0/best.pth"
    wrd_embed_size: 512
    wrd_hidden_size: 512
    spatial_size: 8
    num_cats: 100              # Number of catergories: 91 (actually)
    cat_embed_size: 256
    cat_pad_id: 0              # 1-91 is used

